### ISSUE TITLE
Create task/scripts to start/restart/stop Fedora

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/ansible-role-fedora-commons#1]
[Fedora 4 Deployment Documentation](https://wiki.duraspace.org/display/FEDORA47/Deploying+Fedora+4+Complete+Guide#)

Some recommended [Fedora JVM settings](https://wiki.duraspace.org/display/FEDORA47/Java+HotSpot+VM+Options+recommendations) we can look to for reference.

**Comment by jhriv** [comment]
The role, currently, does not include a start/stop script, nor does this role start/stop the fedora service.

When it does either of those things, we'll be certain to use the suggested startup options.

**Comment by mcritchlow** [comment]
Yep, I should have labeled this appropriately. Just wanted to have a ticket documenting the need, not that this was a bug.

**Comment by gamontoya** [comment]
@mcritchlow Closeable? I'd close it, but I don't have the option.

**Comment by mcritchlow** [comment]
Yup
